// Generated by scripts/fetch-fonts.mjs. Do not edit.
// The Latin files load through next/font/local so they are hashed and
// preloaded. fonts.css adds the other subsets and builds the --font-* variables.
import localFont from "next/font/local";

export const jetbrainsMono = localFont({
  src: [
    { path: "./jetbrains-mono-latin.woff2", weight: "400", style: "normal" },
    { path: "./jetbrains-mono-latin.woff2", weight: "500", style: "normal" },
    { path: "./jetbrains-mono-latin.woff2", weight: "600", style: "normal" },
    { path: "./jetbrains-mono-latin.woff2", weight: "700", style: "normal" },
  ],
  display: "swap",
  variable: "--font-jetbrains-latin",
  adjustFontFallback: false,
  declarations: [
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});

export const plexMono = localFont({
  src: [
    { path: "./ibm-plex-mono-latin-400.woff2", weight: "400", style: "normal" },
    { path: "./ibm-plex-mono-latin-500.woff2", weight: "500", style: "normal" },
    { path: "./ibm-plex-mono-latin-600.woff2", weight: "600", style: "normal" },
    { path: "./ibm-plex-mono-latin-700.woff2", weight: "700", style: "normal" },
  ],
  display: "swap",
  variable: "--font-plex-mono-latin",
  adjustFontFallback: false,
  declarations: [
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
  ],
});

export const plexSans = localFont({
  src: [
    { path: "./ibm-plex-sans-latin.woff2", weight: "300", style: "normal" },
    { path: "./ibm-plex-sans-latin.woff2", weight: "400", style: "normal" },
    { path: "./ibm-plex-sans-latin.woff2", weight: "500", style: "normal" },
    { path: "./ibm-plex-sans-latin.woff2", weight: "600", style: "normal" },
    { path: "./ibm-plex-sans-latin.woff2", weight: "700", style: "normal" },
  ],
  display: "swap",
  variable: "--font-plex-sans-latin",
  adjustFontFallback: false,
  declarations: [
    { prop: "unicode-range", value: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD" },
    { prop: "font-stretch", value: "100%" },
  ],
});
