// Embeds the OG cards' Noto Sans fonts as base64 in generated/og-fonts.ts, so
// lib/og.tsx never reads the filesystem at request time: the Cloudflare Worker
// that serves the site has none. Runs before `next build` and `next dev`.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const b64 = (path) => readFileSync(path).toString('base64');

mkdirSync('generated', { recursive: true });
writeFileSync(
  'generated/og-fonts.ts',
  `// Generated by scripts/og-assets.mjs. Do not edit.
export const NOTO_SANS_REGULAR = "${b64('public/fonts/NotoSans-Regular.ttf')}";
export const NOTO_SANS_BOLD = "${b64('public/fonts/NotoSans-Bold.ttf')}";
`,
);
